@startuml
left to right direction
actor Mahasiswa

rectangle "Student Task Tracker" {
  usecase "Mengelola Data Tugas" as UC1
  usecase "Lihat Daftar Tugas" as UC2
  usecase "Hapus Tugas" as UC3
  usecase "Ubah Tugas" as UC4
  usecase "Tambah Tugas" as UC5
}

Mahasiswa --> UC1
UC1 <.. UC2 : <<extend>>
UC1 <.. UC3 : <<extend>>
UC1 <.. UC4 : <<extend>>
UC1 <.. UC5 : <<extend>>
@enduml