@startuml
left to right direction
actor Mahasiswa

rectangle "Student Task Tracker" {
  usecase "Menggunakan Focus Mode" as UC1
  usecase "Simpan Riwayat Pengerjaan" as UC2
  usecase "Mulai Timer Pomodoro" as UC3
}

Mahasiswa --> UC1
UC1 ..> UC2 : <<include>>
UC1 <.. UC3 : <<extend>>
@enduml