@startuml
left to right direction
skinparam packageStyle rectangle
actor Mahasiswa

rectangle "Student Task Tracker" {
  ' --- 1. Autentikasi ---
  usecase "Melakukan Autentikasi" as UC_Auth
  usecase "Register" as UC_Reg
  usecase "Login" as UC_Login

  ' --- 2. Kelola Data Tugas ---
  usecase "Mengelola Data Tugas" as UC_Task
  usecase "Lihat Daftar Tugas" as UC_View
  usecase "Tambah Tugas" as UC_Add
  usecase "Ubah Tugas" as UC_Edit
  usecase "Hapus Tugas" as UC_Del

  ' --- 3. Prioritas Tugas ---
  usecase "Melihat Daftar Prioritas Tugas" as UC_Prio

  ' --- 4. Focus Mode ---
  usecase "Menggunakan Focus Mode" as UC_Focus
  usecase "Mulai Timer Pomodoro" as UC_Timer
  usecase "Simpan Riwayat Pengerjaan" as UC_History

  ' --- 5. Kolaborasi Tugas ---
  usecase "Mengelola Kolaborasi Tugas" as UC_Collab
  usecase "Import Tugas via Kode" as UC_Imp
  usecase "Generate Kode Tugas" as UC_Gen
}

' =========================================
' RELASI AKTOR KE MENU UTAMA (BUSINESS REQ)
' =========================================
Mahasiswa --> UC_Auth
Mahasiswa --> UC_Task
Mahasiswa --> UC_Prio
Mahasiswa --> UC_Focus
Mahasiswa --> UC_Collab

' =========================================
' RELASI INCLUDE & EXTEND TIAP FITUR
' =========================================
' Relasi Autentikasi
UC_Auth <.. UC_Reg : <<extend>>
UC_Auth ..> UC_Login : <<include>>

' Relasi Kelola Tugas
UC_Task <.. UC_View : <<extend>>
UC_Task <.. UC_Add : <<extend>>
UC_Task <.. UC_Edit : <<extend>>
UC_Task <.. UC_Del : <<extend>>

' Relasi Focus Mode
UC_Focus <.. UC_Timer : <<extend>>
UC_Focus ..> UC_History : <<include>>

' Relasi Kolaborasi
UC_Collab <.. UC_Imp : <<extend>>
UC_Collab <.. UC_Gen : <<extend>>

@enduml